core/urls.py
from django.urls import path
from .views import (
    CheckoutView,
    ItemDetailView,
    HomeView,
    Products_Home,
    Products_ByCat,
    Products_AllDesc,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    Landing,
    show_Categories
)

app_name = 'core'

urlpatterns = [
    path('', Landing, name='home'),
    path('products/', Products_Home, name='products'),
    path('products_bycat/<cat_id>/', Products_ByCat, name='prod_Cat'),
    path('products_alldesc/<cat_id>/', Products_AllDesc, name='prod_Desc'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView, name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django_extensions.db.fields import AutoSlugField
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum

from django.shortcuts import reverse
from django_countries.fields import CountryField
# from django.db.models.constraints import UniqueConstraint

from mptt.models import MPTTModel, TreeForeignKey
from django.db import models
from .fields import ImageThumbsField


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

VOORRAADSTATUS = (
    ('V', 'op voorraad'),
    ('I', 'in bestelling'),
    ('T', 'tijdelijk niet leverbaar')
    )

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

SIZES = (
    {'code':'thumb','wxh':'69x100','resize':'crop'},
    {'code':'galry','wxh':'400x580','resize':'crop'},
    {'code':'detail','wxh':'552x800'},
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Category(MPTTModel):
    ctg_Title = models.CharField(max_length=85, unique=True)
    ctg_Name_Long = models.TextField(blank=True, null=True)
    ctg_Slug = AutoSlugField(populate_from=('ctg_Title',))
    parent = TreeForeignKey(
        'self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    level = models.PositiveIntegerField(default=0)
    lft = models.PositiveIntegerField(default=0)
    rght = models.PositiveIntegerField(default=0)
    level = models.PositiveIntegerField(default=0)
    tree_id = models.PositiveIntegerField(default=0)

    class MPTTMeta:
        order_insertion_by = ['ctg_Title']

    class Meta:
        verbose_name = 'categorie'
        verbose_name_plural = 'categorien'

    def __str__(self):
        return self.ctg_Title


class Brand(models.Model):
    brd_Name = models.CharField(max_length=85)
    brd_Name_Long = models.CharField(max_length=250, blank=True, null=True)
    brd_Ctrl = models.CharField(max_length=30, blank=True, null=True)
    brd_Is_Show = models.BooleanField(default=True)
    brd_ImagePath = models.ImageField(max_length=250, blank=True, null=True)
    brd_Descr = models.TextField(blank=True, null=True)
    brd_IndexNr = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Merk'
        verbose_name_plural = 'Merken'

    def __str__(self):
        return self.brd_Name


class Item(models.Model):
    title = models.CharField('Titel', max_length=100, help_text='Titel waarmee u het product in de catelogus wilt weergeven')
    price = models.FloatField(verbose_name='Prijs')
    discount_price = models.FloatField(blank=True, null=True, verbose_name='Discount Prijs')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True)
    slug = AutoSlugField(populate_from=('title'))
    itm_Categories = models.ManyToManyField(Category, verbose_name='Categorie')
    description = models.TextField(blank=True, default='', verbose_name='Omschrijving', help_text='Product omschrijving')
    image = ImageThumbsField(verbose_name='Hoofd afbeelding', max_length=250, blank=True, null=True, sizes=SIZES, help_text='Afbeelding die in catalogus gebruikt wordt')
    itm_KeyWords = models.TextField(blank=True, default='', verbose_name='Sleutelwoorden', help_text='Woorden waarmee zoekopdrachten worden vergemakkelijkt')
    itm_Name_Long = models.CharField('Korte naam', max_length=250, default='', blank=True, help_text='Naam/aanduiding, korter dan titel, voor in menu\'s en lijsten')
    itm_Pitch = models.TextField(
        blank=True, default='', verbose_name='Pitch', help_text='Verkoop pitch bij dit artikel')
    itm_Materiaal = models.CharField('Materiaal', max_length=120, default='', blank=True, help_text='Materiaal waaruit het product is vervaardigd')
    itm_Afmetingen = models.CharField('Afmetingen lxhxb', max_length=85, default='', blank=True, help_text='Afmetingen van het product (lxhxb)')
    itm_VoorraadStatus = models.CharField('Voorraad status', choices=VOORRAADSTATUS, max_length=1, default='V' )
    itm_LeverTijd = models.CharField('Levertijd (dagen)', max_length=45, default='', blank=True)
    itm_IndexNr = models.IntegerField('Volgorde', blank=True, default=0, help_text='Volgorde van weergave')
    itm_Ctrl = models.CharField('Controlfield', max_length=30, blank=True, default='', help_text='Systeemveld, Dit veld niet wijzigen')
    itm_Is_Show = models.BooleanField('Tonen J/N', blank=True, default=True, help_text='Door uit te zetten wordt dit product niet meer getoond (gedeactiveerd)')
    itm_Is_Frontpage = models.BooleanField('Voorpagina J/N (Featured)' , blank=True, default=True)
    itm_Is_Sale = models.BooleanField('Sale J/N', blank=True, default=True)
    itm_Is_Newasset = models.BooleanField('Nieuw binnen J/N', blank=True, default=True)
    itm_Brand_id = models.ForeignKey(
        Brand, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Merk')

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Producten'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class FotoSet(models.Model):
    fst_Title = models.CharField(
        default='', max_length=100, verbose_name='Titel', blank=True, help_text='Bijvoorbeeld: Vooraanzicht, zijkant, enz.')
    fst_Name_Plural = models.CharField(
        default='', max_length=100, blank=True, verbose_name='Meervoudsnaam', help_text='Om event te gebruiken in text genarator')
    itm_Fk_Item_id = models.ForeignKey(
        Item, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Bij artikel', help_text='Artikel waarbij deze foto hoort')
    fst_Slug = AutoSlugField(populate_from=(
        'fst_Title'), editable=False, verbose_name='Slug code', help_text='Speciale itemcode, dit veld niet aanpassen')
    fst_Description = models.TextField(
        blank=True, default='', verbose_name='Omschrijving')
    fst_Is_Feature = models.BooleanField(default=False, blank=True, verbose_name='Is hoofdfoto', help_text='Gebruik deze foto in de catalogus')
    fst_Is_Show = models.BooleanField(blank=True, default=True, verbose_name='Tonen', help_text='Foto al dan niet tonen in de fotoset')
    fst_Image = models.ImageField(
        max_length=250, blank=True, null=True, verbose_name='Afbeelding')
    fst_Name_Long = models.CharField(
        max_length=250, blank=True, default='', verbose_name='Naam uitgebreid')
    fst_IndexNr = models.IntegerField(
        blank=True, default=0, verbose_name='Volgnummer')
    fst_Ctrl = models.CharField(max_length=30, default='', blank=True, verbose_name='Beheercodes',
                                help_text='Dit veld alleen door de administrator te gebruiken')

    class Meta:
        verbose_name_plural = 'FotoSets'

    def __str__(self):
        return self.fst_Title


class Type(models.Model):
    ty_Nm = models.CharField(max_length=85, blank=True, null=True)
    ty_Descr = models.CharField(max_length=85, blank=True, null=True)
    ty_Ctrl = models.CharField(max_length=30, blank=True, null=True)
    ty_Is_active = models.BooleanField(default=True)


class Type_Item(models.Model):
    ti_Nm = models.CharField(max_length=85, blank=True, null=True)
    ti_TextVal = models.CharField(max_length=85, default='text value')
    ti_Ctrl = models.CharField(max_length=30, blank=True, null=True)
    ti_Is_active = models.BooleanField(default=True)
    ti_Type = models.ForeignKey(Type, on_delete=models.CASCADE)
    ti_Descr = models.CharField(max_length=85, blank=True, null=True)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="nl">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>

    {% include 'css.html' %}
      
    {% block extra_head %} 
    {% endblock %} 
    
    <style type="text/css">
    @media (min-width: 768px) {
  /* For show 3 advance 1 corousel */  

		.carousel-inner .carousel-item.active,
		.carousel-inner .carousel-item-next,
		.carousel-inner .carousel-item-prev {
		  	display: flex;
		}
		
		.carousel-inner .carousel-item-right.active,
		.carousel-inner .carousel-item-next {
		  	transform: translateX(33%);
		}
		
		.carousel-inner .carousel-item-left.active, 
		.carousel-inner .carousel-item-prev {
		  	transform: translateX(-33%);
		}
		  
		.carousel-inner .carousel-item-right,
		.carousel-inner .carousel-item-left{ 
		  	transform: translateX(0);
		  
		}
		
		.movie-img {
			height:200px;width: 150px;background-color:  aqua;overflow: hidden;background-image: url("https://i.hizliresim.com/mX07R4.png");
			background-repeat:no-repeat;
			background-size: cover;
			object-fit: fill;
		}

		.movie-title {
			height: 40px; width:150px;background-color: black;overflow: hidden;
		}
	}
    </style>
 

    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }
        
        @media (max-width: 740px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
        
        @media (min-width: 800px) and (max-width: 850px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>

 </head>

<body>

    {% include "above_navbar.html" %} 
    
    {% include "navbar.html" %}


    <div class="">
        {% if messages %} 
        
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;
          </span>
        </button>
        </div>
        {% endfor %} 
        {% endif %}
    </div>

    {% block content %} 
    
    {% endblock content %} 
    
    {% block extra_body %} 
    {% endblock %} 
    
    {% include "footer.html" %} 
    
    {% include "scripts.html" %} 
    
    {% block extra_scripts %} 
    {% endblock extra_scripts %}

</body>

</html>

templates/home.html
{% extends "base.html" %}

{% load mptt_tags %}

{% block content %}
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mb-5">

      <!-- Navbar brand 
      <span class="navbar-brand">Categorie&euml;n:</span>
        -->

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">



        <!--o- #$# Categorie deel navbar -->

        <ul class="navbar-nav mr-auto">
          {% recursetree thecategories %}
          {% if node.level == 0 %}
          {% if not node.is_leaf_node %}
          <!-- Let op: <li> tag wordt steeds onderaan aangevuld, ander werkt het niet...-->
          <li class="dropdown nav-item">
            <a href="/products_bycat/{{ node.id }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">
              <span class="mainBarItem">{{ node.ctg_Title }}<span class="caret"></span> </span></a>
              <ul class="children dropdown-menu">
                <li><a href="/products_alldesc/{{ node.id }}">Alle {{ node.ctg_Title }} ></a>

          {% else %}
          <li><a href="/products_bycat/{{ node.id }}" class="mainBarItem">{{ node.ctg_Title }}</a>
            {% endif %}

            {% else %}
            {% if not node.is_leaf_node %}
              <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false">
                  <span class="nav-label">{{ node.ctg_Title }}&nbsp;&gt;</span><span class="caret"></span></a>
                <ul class="children dropdown-menu">
                  <li><a href="/products_alldesc/{{ node.id }}">Alle {{ node.ctg_Title }} ></a>
    
            {% else %}
    
              <li><a href="/products_bycat/{{ node.id }}">{{ node.ctg_Title }}</a>
            {% endif %}
            {% endif %}

            {% if not node.is_leaf_node %}
              {{ children }}
            </ul>
            {% endif %}
          </li>

          {% endrecursetree %}
        </ul>







        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      {% if object_list.count == 0 %}
      <h2>No items in object list</h2>
      {% endif %}

      <div class="row wow fadeIn">


        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% if item.image %}
              <img src="{{ item.image.url_galry }}" class="card-img-top">
              {% endif %}
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                <div class="row" style="text-overflow: ellipsis;">
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                  </div>
                  {% if item.itm_Is_Newasset %}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">
                      NIEUW
                    </span>
                  {% endif %}
                  {% if item.itm_Is_Sale %}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">
                      Afgeprijst
                    </span>
                  {% endif %}
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>&euro;
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>

{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">&euro;{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-&euro;{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>&euro;{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                &euro;{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving &euro;{{ order_item.get_amount_saved }}</span>
            {% else %}
                &euro;{{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-&euro;{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>&euro;{{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/prodshow.html
{% load static %}

<!-- #$# begin prodshow -->

<!-- In deze rij de active afbeelding -->
        <!-- 1. Insert the first product image to the gallery -->
        {% if object.image %}
        <div class="zi-show" href="{{ object.image.url}}">
            <img src="{{ object.image.url}}" alt="{{obj.fst_Title}}" id="zi-show-img">
        </div>
        {% endif %}
<!-- 2. Create a thumbnail carousel that enable the customers to switching between product images by clicking the thumbnail images. -->
    <div class="zi-small-img" style="display: block; width: 100%" >
        <!--
            <img src="{% static 'img/showProd/online_icon_right@2x.png' %}" class="icon-left" alt=""        id="prev-img">
        -->

        <div class="zi-small-container" >
            <!-- In deze div wordt in main.js een carousel achtig ding gedaan -->
            <div id="zi-small-img-roll">
                    {% for obj in object.fotoset_set.all %}
                        <div style="max-width: 60px; height: 60px; overflow: hidden; display: inline-block;">
                    		{% if obj.fst_Image %}
                            <img src="{{ obj.fst_Image.url}}" class="zi-show-zi-small-img img-fluid" alt="" >
                            {% endif %}
                        </div>
                    {% endfor %}
            </div>
        </div>
        <!--
        <img src="{% static 'img/showProd/online_icon_right@2x.png' %}" class="icon-right" alt="" id="next-img">
        -->
</div>

	
	
	
	

templates/prodshow02.html
{% load static %}

<!-- #$# begin prodshow -->

<!-- In deze rij de active afbeelding -->
<!-- 1. Insert the first product image to the gallery -->
<div class="row " >
    {% if object.image %}
    <div class="col-lg-9 col-md-12 h-50 d-inline-block theImage" id="zi-show"  >
        <img src="{{ object.image.url}}" alt="{{obj.fst_Title}}"
            style="max-width: 100%; height: auto; " id="zi-show-img"
            class="img-fluid">
    </div>
    <!-- De vergrootglas -->
    <div class="col-lg-3">
        <div class="row h-50 d-inline-block">
            <!-- werd oorspr gebruikt in zoom image -->
            <div id="zi-showpanel" style="width: 100%; heigth: 100%;" >
            		{% if object.itm_Brand_id.brd_ImagePath %}
			        	<img src="{{ object.itm_Brand_id.brd_ImagePath.url }}" class="img-fluid"  style="float: right;" alt="">
					{% endif %}
            </div>
        </div>

        <div class="row">
            <!-- In deze div wordt in main.js een carousel achtig ding gedaan -->
            <!-- <div id="zi-small-img-roll">  -->
            <table class="table">
                <tbody>
                    <tr>
		                <td>
							<!-- De hoofdImage als thumbnail toevoegen -->
	                        <img src="{{ object.image.url }}"
	                            class="zi-small-img img-fluid"
	                            style="max-width: 70px; max-height: 70px; overflow: hidden; display: inline-block; border: solid 3px blue"
	                            alt="Main">
		                </td>    

                        {% for obj in object.fotoset_set.all %} 
                        {% if obj.fst_Image %}
                        <td>
                        <img src="{{ obj.fst_Image.url }}"
                            class="zi-small-img img-fluid"
                            style="max-width: 70px; max-height: 70px; overflow: hidden; display: inline-block;"
                            alt="">
                         </td> 
                         <!-- add 1 voor hoofd image die apart is toegevoegd -->
                        {% if forloop.counter|add:"1"|divisibleby:3 %}
		                    </tr>
		                    <tr>
	                    {% endif %} {% endif %} {% endfor %}
                    </tr>
                </tbody>
            </table>
            <!-- </div> -->
        </div>
    </div>
    {% endif %}
</div>

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}